<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-79SVG1A0" failures="1" tests="5" name="Personal Loan" time="0.105" errors="0" timestamp="2025-02-05T20:50:37 ICT">
  <testcase classname="test.day1" name="Demo" time="0.026">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.day2" name="ploan" time="0.003"/>
  <testcase classname="test.day4" name="MobileloginHomeLoan" time="0.003"/>
  <testcase classname="test.day4" name="loginAPIHomeLoan" time="0.001"/>
  <testcase classname="test.day4" name="webloginHomeLoan" time="0.002"/>
  <testcase classname="test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
